title: Shmoile Afzal # your name (or website title) here
logo: "https://media.licdn.com/dms/image/D4D03AQHuASB7lTXOWA/profile-displayphoto-shrink_400_400/0/1708491497647?e=1720656000&v=beta&t=WBbtTBA3IADu6UoNgUQkPEEPcs5qOnrZwcFgTZxEQ6g" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven Accountant with a passion to drive business growth and efficiency! 
  <br><br>
  <a href="https://www.linkedin.com/in/shmoile-afzal/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
